name: telemarketing-optimization
channels:
  - defaults
dependencies:
  - pandas
  - python==3.10
  - black
  - scikit-learn
  - ipykernel
  - xgboost
  - matplotlib
  - seaborn
  - plotly
  - nbformat
  - flask
  - requests
  - uvicorn